CREATE DATABASE Emprego;
Go

USE Emprego;
GO 

CREATE TABLE TipoUsuario(
		IdTipoUsuario INT PRIMARY KEY IDENTITY,
		TituloTipoUsuario VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Usuario(
		IdUsuario INT PRIMARY KEY IDENTITY,
		IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
		NomeUsuario VARCHAR(200) NOT NULL,
		SenhaUsuario VARCHAR(255) NOT NULL,
		Email VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE Aluno(
		IdAluno INT PRIMARY KEY IDENTITY,
		IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
		NumeroMatricula CHAR(10) NOT NULL UNIQUE,
		Curso VARCHAR(200) NOT NULL,
		CPF CHAR(11) NOT NULL UNIQUE,
		DataNascimento DATE NOT NULL,
		Curriculo VARBINARY(MAX)
);
GO

CREATE TABLE Empresa(
		IdEmpresa INT PRIMARY KEY IDENTITY,
		IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
		CNPJ CHAR(14) NOT NULL UNIQUE,
		CEP CHAR(8) NOT NULL UNIQUE,
		Contato CHAR(11) NOT NULL UNIQUE,
		Descricao VARCHAR(500) NOT NULL,
		Logo VARBINARY(MAX) NOT NULL
);
GO

CREATE TABLE FuncionarioEmpresa(
		IdFuncionarioEmpresa INT PRIMARY KEY IDENTITY,
		IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
		IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
		NumeroFuncionario INT 
);
GO

CREATE TABLE Vaga(
		IdVaga INT PRIMARY KEY IDENTITY,
		IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
		IdFuncionarioEmpresa INT FOREIGN KEY REFERENCES FuncionarioEmpresa(IdFuncionarioEmpresa),
		NomeVaga VARCHAR(200) NOT NULL,
		DescricaoVaga VARCHAR(500) NOT NULL,
		DisponibilidadeVaga DATE NOT NULL,
		CandidatosVaga INT
);
GO

CREATE TABLE Skill(
		IdSkill INT PRIMARY KEY IDENTITY,
		IdVaga INT FOREIGN KEY REFERENCES Vaga(IdVaga),
		IdAluno INT FOREIGN KEY REFERENCES Aluno(IdAluno),
		NomeSkill VARCHAR(200) NOT NULL
);
GO

CREATE TABLE VagaSkill(
		IdVagaSkill INT PRIMARY KEY IDENTITY,
		IdVaga INT FOREIGN KEY REFERENCES Vaga(IdVaga),
		IdSkill INT FOREIGN KEY REFERENCES Skill(IdSkill)
);
GO

CREATE TABLE AlunoSkill(
		IdAlunoSkill INT PRIMARY KEY IDENTITY,
		IdAluno INT FOREIGN KEY REFERENCES Aluno(IdAluno),
		IdSkill INT FOREIGN KEY REFERENCES Skill(IdSkill)
);
GO

CREATE TABLE Inscricao(
		IdInscricao INT PRIMARY KEY IDENTITY,
		IdAluno INT FOREIGN KEY REFERENCES Aluno(IdAluno),
		Admicao BIT DEFAULT (0),
		Descricao VARCHAR(500) NOT NULL
);
GO

CREATE TABLE Administrador(
	IdAdministrador INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)
); 
GO


